### ISSUE TITLE
Review :)

### ISSUE THREAD

**Issue by lkostrowski** [eisenek/pokemon_project#1]
Hej

Robiłem Ci review ostatnio szybkie, też odpiszę.

Jeżeli chodzi o boilerplate - spoko, że potrafisz takie coś skonfigurować, jednak właśnie utrzymanie wbrew pozorom jest kosztowne - troche bardziej współczesne jest wyciąganie "konfiguracji do paczek" jak np `create-react-app` - tam można zrobić `eject` ale można też trzymać pojedyncze dependency do `react-scripts` bez instalowania wszystkiego potrzebnego by mieć podstawową apkę Reactową. 
Oczywiście takich boilerplatów jest wiele, ale to troche jak z autorskimi CMSami - każdy robi to samo, ale szybko są porzucane. Wg mnie lepiej zaufać czemuś co ma dziesiątki tysięcy "gwiazdek" bo będzie poprawiane przez community, a nie utrzymywane przez jedną osobę. 

A takie procesy budowania też się zmieniają, wiadomo, chcesz dodać nowe narzędzie do jakieś analizy czegośtam, to potrzebujesz webpacka nowszego, a ten z kolei nie jest wspierany przez cośtam, więc musisz podnieść wersję itd itd.

Co do niepotrzebnego serwera - no to jest właśnie kwestia na rozmowę, bo z drugiej strony - treść zadania podana, jest YAGNI ;)

Oczywiście boilerplate nie jest czymś dyskwalikifukącym

Co do TS - tu jest mój błąd, wybacz. Oczywiście jest TS, ale masz zrobią konfigurację jakbyś pisał w JS. Dla mnie np niewybaczalne jest użycie `noImplicitAny` - to jest flaga która jest używana do migracji JSa na TSa. Jak to wyłączysz i zostawisz "prawilny" strict mode, aplikacja Ci się nie skompiluje.

Pisałem "brak ts" i "brak proptypes" patrząc na 
https://github.com/eisenek/pokemon_project/blob/master/src/app/components/pokemon-list.tsx

Gdzie korzystasz z nieotypowanych props.

Mam nadzieje że pomogłem - nie lubię tak zostawiać bez odpowiedzi.

Powodzenia

**Comment by eisenek** [comment]
@lkostrowski 

> Oczywiście takich boilerplatów jest wiele, ale to troche jak z autorskimi CMSami - każdy robi to samo, ale szybko są porzucane. Wg mnie lepiej zaufać czemuś co ma dziesiątki tysięcy "gwiazdek" bo będzie poprawiane przez community, a nie utrzymywane przez jedną osobę.

Co rozumiesz przez utrzymanie w tym wypadku? Podbicie wersji reacta? Przy create-react app również musisz się o to troszczyć. Jasne że `eject` i `react-scriptsy` są fancy, ale BUZI - prosta apka, nie wymagająca kombajna, jakim jest create-react-app.

> A takie procesy budowania też się zmieniają, wiadomo, chcesz dodać nowe narzędzie do jakieś analizy czegośtam, to potrzebujesz webpacka nowszego, a ten z kolei nie jest wspierany przez cośtam, więc musisz podnieść wersję itd itd.

'Filozofia' pakietów w node.js zakłada, że każdy z takich pakietów ma swój zestaw zależności, żeby nie wpływać na całość projektu. W takim wypadku jak wspominasz, jeśli nie masz akurat w planie nadrabiać długu technologicznego i nie chcesz podbijać zależności w całym projekcie, tworzysz paczkę dla narzędzia do analizy czegośtam, określasz w zależnościach, że działa z webpackiem nowszym i wrzucasz jako paczkę na repozytorium npm. Przy instalacji każdy z pakietów instaluje swój zestaw zależności, narzędzie importujesz jako moduł i wszystko działa i budujesz projekt w zgodzie SOLID.

> Co do niepotrzebnego serwera - no to jest właśnie kwestia na rozmowę, bo z drugiej strony - treść zadania podana, jest YAGNI ;)

OK. Zamknę dyskusję. Serwer renderuje index.html, bo index.html nie jest serwowany statycznie w tym projekcie.

> Co do TS - tu jest mój błąd, wybacz. Oczywiście jest TS, ale masz zrobią konfigurację jakbyś pisał w JS. Dla mnie np niewybaczalne jest użycie noImplicitAny - to jest flaga która jest używana do migracji JSa na TSa. Jak to wyłączysz i zostawisz "prawilny" strict mode, aplikacja Ci się nie skompiluje.

Tu masz rację, lenistwo :)
